server:
  port : ${PORT:8081}
logging:
  config: classpath:logback/logback.xml
  level:
    com.chat.application: debug
    org:
      atmosphere : warn
spring:
  messages:
    encoding: UTF-8
  mustache:
    check-template-location : false
  jpa.defer-datasource-initialization : true

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser : true
# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  whitelisted-packages : com.vaadin,org.vaadin,dev.hilla,com.example.application

service:
  quota:
    max: 200000
  key:
    openai: testOpenaiKey
  response:
    default: '{"":"对不起，我不允许透露有关的任何消息"}'
  prompt:
    ChatRoom1: "你好"
    ChatRoom2: "你好"
  auth:
    blocklist:
      - '0.0.0.0'
  model:
    ChatRoom1: openai:gpt-3.5-turbo
    #ChatRoom2: baidu:test
    ChatRoom2: openai:gpt-3.5-turbo







